markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:title

rdiscount:
  extensions: [smart]

sass:
  style: :compressed
  sass_dir: _sass


name: WONA
url: http://wona.co.in
gems: [jekyll-paginate]
description: The official news magazine of IIT Roorkee.
paginate: 10
paginate_path: "/page/:num"
