markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:title

rdiscount:
  extensions: [smart]

sass:
  style: :compressed
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

name: WONA
url: http://wona.co.in
gems: [jekyll-paginate]
description: The official news magazine of IIT Roorkee.
paginate: 10
paginate_path: "/page/:num"
